-- Table , 시퀀스 등 구조 정의
DROP SEQUENCE SQ_FAQ;
CREATE SEQUENCE SQ_FAQ START WITH 1 INCREMENT BY 1;

DROP SEQUENCE SQ_CUSTOMER;
CREATE SEQUENCE SQ_CUSTOMER START WITH 1 INCREMENT BY 1;

DROP SEQUENCE SQ_QNA;
CREATE SEQUENCE SQ_QNA START WITH 1 INCREMENT BY 1;

DROP SEQUENCE SQ_FILE;
CREATE SEQUENCE SQ_FILE START WITH 1 INCREMENT BY 1;

DROP SEQUENCE SQ_GALLERY;
CREATE SEQUENCE SQ_GALLERY START WITH 1 INCREMENT BY 1;

DROP SEQUENCE SQ_TUTORIAL;
CREATE SEQUENCE SQ_TUTORIAL START WITH 1 INCREMENT BY 1;

DROP SEQUENCE SQ_RESERVATION;
CREATE SEQUENCE SQ_RESERVATION START WITH 1 INCREMENT BY 1;

DROP TABLE TB_FAQ CASCADE CONSTRAINT;
DROP TABLE TB_CUSTOMER CASCADE CONSTRAINT;
DROP TABLE TB_QNA CASCADE CONSTRAINT;

DROP TABLE TB_FILE CASCADE CONSTRAINT;
DROP TABLE TB_GALLERY CASCADE CONSTRAINT;
DROP TABLE TB_TUTORIAL CASCADE CONSTRAINT;
DROP TABLE TB_RESERVATION CASCADE CONSTRAINT;

CREATE TABLE TB_FAQ
(
    NO          NUMBER NOT NULL PRIMARY KEY,
    TITLE       VARCHAR2(255),
    CONTENT     VARCHAR2(255),
    FEATURE     VARCHAR2(255),
    DELETE_YN   VARCHAR2(1) DEFAULT 'N',
    INSERT_TIME VARCHAR2(255),
    UPDATE_TIME VARCHAR2(255),
    DELETE_TIME VARCHAR2(255)
);

CREATE TABLE TB_CUSTOMER
(
    CID         NUMBER NOT NULL PRIMARY KEY,
    FIRST_NAME  VARCHAR2(255),
    LAST_NAME   VARCHAR2(255),
    EMAIL       VARCHAR2(255),
    PHONE       VARCHAR2(255),
    DELETE_YN   VARCHAR2(1) DEFAULT 'N',
    INSERT_TIME VARCHAR2(255),
    UPDATE_TIME VARCHAR2(255),
    DELETE_TIME VARCHAR2(255)
);


CREATE TABLE TB_QNA
(
    QNO         NUMBER NOT NULL PRIMARY KEY,
    QUESTION    VARCHAR2(255),
    ANSWER      VARCHAR2(255),
    QUESTIONER  VARCHAR2(255),
    ANSWERER    VARCHAR2(255),
    DELETE_YN   VARCHAR2(1) DEFAULT 'N',
    INSERT_TIME VARCHAR2(255),
    UPDATE_TIME VARCHAR2(255),
    DELETE_TIME VARCHAR2(255)
);

-- Upload Table
CREATE TABLE TB_FILE
(
    FID          NUMBER NOT NULL PRIMARY KEY,
    FILE_TITLE   VARCHAR2(1000),
    FILE_CONTENT VARCHAR2(1000),
    FILE_NAME    VARCHAR2(1000),
    FILE_TYPE    VARCHAR2(1000),
    FILE_DATA    BLOB,
    DELETE_YN    VARCHAR2(1) DEFAULT 'N',
    INSERT_TIME  VARCHAR2(255),
    UPDATE_TIME  VARCHAR2(255),
    DELETE_TIME  VARCHAR2(255)
);

-- Upload Gallery Table
CREATE TABLE TB_GALLERY
(
    GID                  NUMBER NOT NULL PRIMARY KEY,
    GALLERY_TITLE        VARCHAR2(1000),
    GALLERY_FILE_NAME    VARCHAR2(1000),
    GALLERY_TYPE         VARCHAR2(1000),
    GALLERY_DATA         BLOB,
    DELETE_YN            VARCHAR2(1) DEFAULT 'N',
    INSERT_TIME          VARCHAR2(255),
    UPDATE_TIME          VARCHAR2(255),
    DELETE_TIME          VARCHAR2(255)
);

-- Upload TB_TUTORIAL Excel Table
CREATE TABLE TB_TUTORIAL
(
    ID                   NUMBER NOT NULL PRIMARY KEY,
    TITLE                VARCHAR2(1000),
    DESCRIPTION          VARCHAR2(1000),
    PUBLISHED            VARCHAR2(1000),
    DELETE_YN            VARCHAR2(1) DEFAULT 'N',
    INSERT_TIME          VARCHAR2(255),
    UPDATE_TIME          VARCHAR2(255),
    DELETE_TIME          VARCHAR2(255)
);

-- 예약 테이블
CREATE TABLE TB_RESERVATION
(
    RID                  NUMBER NOT NULL PRIMARY KEY,
    EMAIL                VARCHAR2(1000),
    NAME                 VARCHAR2(1000),
    SIGHTS               VARCHAR2(1000), -- 관광지
    SELECTED_DATE        VARCHAR2(1000), -- 시작날짜
    RESERVATION_YN       VARCHAR2(1) DEFAULT 'N', -- 예약 유무
    ADDRESS              VARCHAR2(1000), -- 주소
    PHONE                VARCHAR2(1000), -- 전화번호
    DELETE_YN            VARCHAR2(1) DEFAULT 'N',
    INSERT_TIME          VARCHAR2(255),
    UPDATE_TIME          VARCHAR2(255),
    DELETE_TIME          VARCHAR2(255)
);










